### PR TITLE
DO NOT MERGE: Testing compatibility with NumPy 1.14 on Windows

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jakirkham** [comment]
I think this would need to add `conda-forge/label/broken` to `channels/sources` to work the way I'm guessing it is intended. Will also need to include `conda-forge` and `defaults` when making that change.

**Comment by jjhelmus** [comment]
@jakirkham good call, I missed that numpy 1.14 had been moved to `broken`

**Comment by jjhelmus** [comment]
This is not going to work, there are too many broken packages in `broken`!  Let me move those packages into a different channel and try again.

**Comment by jakirkham** [comment]
That or change the priority. Would put broken after cf personally.

**Comment by jjhelmus** [comment]
The passing Python 3.6 build gives me enough to work with.  NumPy 1.14 is fine for compiling C extensions, the issue, conda-forge/numpy-feedstock#79, is when Fortran code is present.

**Comment by jjhelmus** [comment]
Testing done, closing.

**Pull request closed without merging**
