### PR TITLE
Build with numpy 1.16 to avoid Numpy warning

### PR DESCRIPTION
**Pull request by hmaarrfk**
…nda-forge-pinning 2020.09.04.10.00.02

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
i'm trying to get rid of a numpy incompatibility warning i'm getting.

Pretty elusive.

**Comment by hmaarrfk** [comment]
In conjunction with: https://github.com/conda-forge/scikit-image-feedstock/pull/64

it seems that the warning I was getting goes away when I used docker t obuild this on my local machine.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by grlee77** [comment]
Thanks @hmaarrfk, let's try it and see if it resolves the issue you are seeing.

**Comment by hmaarrfk** [comment]
Thanks @grlee77 this indeeded gets rid of my warning

```
pytest -Werror tests

../../miniconda3/envs/mcam_dev/lib/python3.7/site-packages/skimage/feature/__init__.py:3: in <module>
    from ._canny import canny
../../miniconda3/envs/mcam_dev/lib/python3.7/site-packages/skimage/feature/_canny.py:18: in <module>
    from ..filters import gaussian
../../miniconda3/envs/mcam_dev/lib/python3.7/site-packages/skimage/filters/__init__.py:4: in <module>
    from .edges import (sobel, sobel_h, sobel_v,
../../miniconda3/envs/mcam_dev/lib/python3.7/site-packages/skimage/filters/edges.py:18: in <module>
    from ..restoration.uft import laplacian
../../miniconda3/envs/mcam_dev/lib/python3.7/site-packages/skimage/restoration/__init__.py:7: in <module>
    from ._denoise import (denoise_tv_chambolle, denoise_tv_bregman,
../../miniconda3/envs/mcam_dev/lib/python3.7/site-packages/skimage/restoration/_denoise.py:7: in <module>
    import pywt
../../miniconda3/envs/mcam_dev/lib/python3.7/site-packages/pywt/__init__.py:16: in <module>
    from ._extensions._pywt import *
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

__init__.pxd:918: RuntimeWarning

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================= 1 failed in 1.89s =========================================

```

**Pull request merged**
