### PR TITLE
Add freethreading support

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Latest release has wheels.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by rgommers** [comment]
Thanks @isuruf! 

It's not clear to me why the Linux aarch64 job for Python 3.12 failed with the below issue, while all the other aarch64 jobs passed. Is that a known issue?
```
Executing transaction: ...working... done
export PREFIX=/home/conda/feedstock_root/build_artifacts/pywavelets_1728920050859/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/pywavelets_1728920050859/test_tmp
/home/conda/feedstock_root/build_artifacts/pywavelets_1728920050859/test_tmp/conda_test_runner.sh: line 3: /home/conda/feedstock_root/build_artifacts/pywavelets_1728920050859/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python: cannot execute binary file
WARNING: Tests failed for pywavelets-1.7.0-py312h681ec18_2.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3483, in test
    utils.check_call_env(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 404, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/conda/feedstock_root/build_artifacts/pywavelets_1728920050859/test_tmp/conda_test_runner.sh']' returned non-zero exit status 126.
```

Also, so I learn something here, is there a `conda-smithy` command to generate the added `.ci_support/migrations/python313t.yaml` file?

**Comment by isuruf** [comment]
It was a network failure where `binfmt_misc` registration failed and therefore the x86_64 host does not know how to run aarch64 executable.

I just copied the file from https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/python313t.yaml here.

**Review by rgommers — APPROVED** [review]
That last job built fine but now seems to hang - probably a connection issue, rather than anything wrong. Nothing changed for aarch64 anyway in this PR, so let's ignore it. In it goes!

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
