### PR TITLE
Add @jakirkham

### PR DESCRIPTION
**Pull request by jakirkham**
Add myself as a maintainer.

### CODE REVIEW

**Comment by ocefpaf** [comment]
The Windows failure was just intermittent service issues so I merged.

**Comment by jakirkham** [comment]
Seems reasonable. I should probably have added `[ci skip]` anyways.

**Comment by ocefpaf** [comment]
> Seems reasonable. I should probably have added `[ci skip]` anyways.

Yes and not to be honest. We found so many error to fix when re-building stuff that did not need to be re-built at the time...

**Comment by jakirkham** [comment]
I have wondered with re-rendering if we should really disable CI for this reason. We don't really want to discover that some CI change breaks things in some serious way after we merge.

**Pull request merged**
