### PR TITLE
update to v0.5.0 and use setuptools

### PR DESCRIPTION
**Pull request by grlee77**
As of this release, the build uses setuptools rather than distutils

### CODE REVIEW

**Comment by jakirkham** [comment]
Could you please rebase or cherry-pick the change from PR ( https://github.com/conda-forge/pywavelets-feedstock/pull/6 )? Also, will need to comment `conda inspect linkages` and [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ). Feel free to try `conda smithy rerender --commit` to commit all the re-rendering changes simply.

**Comment by grlee77** [comment]
Thanks @jakirkham.  I did a cherry-pick and rerendered using the command you suggested.  Is this good to merge once all CI are green?

**Comment by jakirkham** [comment]
Somehow `.gitignore` got executable permissions. Could we please revert that?

**Comment by jakirkham** [comment]
Actually so did every other file in this PR AFAICT. Please revert the executable permissions from non-executable things.

**Comment by grlee77** [comment]
okay.  should be back to how it was on the permissions now.  That happened somehow during the rerendering via conda-smithy.  I think it is because the drive I was working on at the time was an NTFS drive mounted on linux and has some strange permission settings.

**Comment by jakirkham** [comment]
> okay. should be back to how it was on the permissions now. That happened somehow during the rerendering via conda-smithy. I think it is because the drive I was working on at the time was an NTFS drive mounted on linux and has some strange permission settings.

Very interesting. Thanks for the info. Do you mind opening an issue over at `conda-smithy`? I'd like to track this down and fix it somehow if possible.

**Comment by grlee77** [comment]
issue opened at conda-forge/conda-smithy#365

**Pull request merged**
